#!/usr/local/perl

#Copyright (c) 2003, The Institute for Genomic Research (TIGR), Rockville, Maryland, U.S.A.  All rights reserved.

use strict;
use FileHandle;

my (%vector,@ag,@gt,@scoreag,@scoregt);

my $no_leaves=10;
my $no_of_trees=10;

return 1;

# this procedure takes exons.dat, genelist and seqs as arguments
# and computes the in-frame hexamer frequencies for exons and the 
# hexamer frequencies for all frames of exons, introns, and intergenic
# DNA; the results are written in 2 files: exon.hexfreq and 
# all.hexfreq
sub hexfreq {

    my ($f,$g,$h)=@_;

    my ($allfreq,$exonfreq,%takegene,%exons);

    # read genes to be considered
    open(F,$g) || die "ERROR 15: Could not open file $g for reading!\n";

    while(<F>) {
	chomp;
	$takegene{$_}++;
    }
    close(F);

    # read exons
    open(F,$f) || die "ERROR 16: Could not open file $f for reading!\n";

    while(<F>) {
	chomp;
	if($_) {
	    my @a=split;
	    if($takegene{$a[0]}) {
		$exons{$a[0]}.=$a[1]." ".$a[2]." ";
	    }
	}
    }

    close(F);

    # initialize hexamer frequencies

    my (@let,$hexamer,%afreq,%efreq);
    $let[0]='A';
    $let[1]='C';
    $let[2]='G';
    $let[3]='T';

    for(my $i1=0;$i1<4;$i1++) {
	for(my $i2=0;$i2<4;$i2++) {
	    for(my $i3=0;$i3<4;$i3++) {
		for(my $i4=0;$i4<4;$i4++) {
		    for(my $i5=0;$i5<4;$i5++) {
			for(my $i6=0;$i6<4;$i6++) {
			    $hexamer=$let[$i1].$let[$i2].$let[$i3].$let[$i4].$let[$i5].$let[$i6];
			    $afreq{$hexamer}=0;
			    $efreq{$hexamer}=0;
			}
		    }
		}
	    }
	}
    }
    

    # compute hexamer frequencies

    open(F,$h) || die "ERROR 17: Could not open file $h for reading!\n";

    while(<F>){
	chomp;
	my @a=split;

	if($takegene{$a[0]}) {
	    my $len=length($a[1]);
	    for(my $i=0;$i+5<$len;$i++) {
		$hexamer=uc(substr($a[1],$i,6));

		$afreq{$hexamer}++;
	    }
	
	    my @valex=split(/ /,$exons{$a[0]});
	    my $frame=0;

	    my ($len,$exon);

	    for(my $i=0;$i<=$#valex;$i+=2) {
		$exon=substr($a[1],$valex[$i]-1,$valex[$i+1]-$valex[$i]+1);
		$len=length($exon);
		for(my $j=$frame;$j+5<$len;$j+=3) { # here I compute the in-frame frequency
		    $hexamer=uc(substr($exon,$j,6));
		    $efreq{$hexamer}++;
		}
		$len-=$frame;
		$frame=(3-($len%3))%3;
	    }
	}
    }

    close(F);

    my $exonfile="exon.hexfreq";
    my $allfile="all.hexfreq";

    for(my $i1=0;$i1<4;$i1++) {
	for(my $i2=0;$i2<4;$i2++) {
	    for(my $i3=0;$i3<4;$i3++) {
		for(my $i4=0;$i4<4;$i4++) {
		    for(my $i5=0;$i5<4;$i5++) {
			for(my $i6=0;$i6<4;$i6++) {
			    
			    $hexamer=$let[$i1].$let[$i2].$let[$i3].$let[$i4].$let[$i5].$let[$i6];
			    $allfreq+=$afreq{$hexamer};
			    $exonfreq+=$efreq{$hexamer};
			}
		    }
		}
	    }
	}
    }

    open(E,">$exonfile") or die "ERROR 18: Could not open file $exonfile for writing!\n";
    open(A,">$allfile") or die "ERROR 19: Could not open file $allfile for writing!\n";

    

    for(my $i1=0;$i1<4;$i1++) {
	for(my $i2=0;$i2<4;$i2++) {
	    for(my $i3=0;$i3<4;$i3++) {
		for(my $i4=0;$i4<4;$i4++) {
		    for(my $i5=0;$i5<4;$i5++) {
			for(my $i6=0;$i6<4;$i6++) {
			    $hexamer=$let[$i1].$let[$i2].$let[$i3].$let[$i4].$let[$i5].$let[$i6];
			    my $freq=$efreq{$hexamer}/$exonfreq;
			    printf E "%s %.10f\n",$hexamer,$freq;
			    $freq=$afreq{$hexamer}/$allfreq;
			    printf A "%s %.10f\n",$hexamer,$freq;
			}
		    }
		}
	    }
	}
    }
    close(E);
    close(A);
}


# this procedure takes exon.hexfreq, all.hexfreq (the files generated by 
# by hexfreq), genelist, exons.dat and sites.scores (the file 
# generated by getsites.pl) as arguments and extract the features for
# the true and false exons; the results are written in 4 files, 
# according with the exon types: firstexons.features, snglexons.features
# internalexons.features and lastexons.features
# as well as the intron features written in introns.features
sub feature_extract {

    my ($c,$d,$e,$f,$g,$h,$max_ex,$max_in)=@_;

    # read genes to be considered

    my %takegene;

    open(F,$c) || die "ERROR 1: Could not open file $c for reading: $!\n";    # genelist
    while(<F>) {
	chomp;
	$takegene{$_}++;
    }
    close(F);

    # read frequencies

    my (%ehexamer,%ahexamer);

    open(F,$d) || die "ERROR 2: Could not open file $d for reading: $!\n";    # exon.hexfreq
    while(<F>) {
	chomp;
	if($_) {
	    my @a=split;
	    $ehexamer{$a[0]}=$a[1];
	}
    }
    close(F);

    open(F,$e) || die "ERROR 3: Could not open file $e for reading: $!\n";    # all.hexfreq

    while(<F>) {
	chomp;
	if($_) {
	    my @a=split;
	    $ahexamer{$a[0]}=$a[1];
	}
    }
    close(F);

    my (@let);

    $let[0]='A';
    $let[1]='C';
    $let[2]='G';
    $let[3]='T';

    for(my $i1=0;$i1<4;$i1++) {
	for(my $i2=0;$i2<4;$i2++) {
	    for(my $i3=0;$i3<4;$i3++) {
		for(my $i4=0;$i4<4;$i4++) {
		    for(my $i5=0;$i5<4;$i5++) {
			for(my $i6=0;$i6<4;$i6++) {
			    my $hexamer=$let[$i1].$let[$i2].$let[$i3].$let[$i4].$let[$i5].$let[$i6];
			    if($ehexamer{$hexamer}==0) {
				$vector{$hexamer}=-15;}
			    else {
				$vector{$hexamer}=log($ehexamer{$hexamer}/$ahexamer{$hexamer});
			    }
			}
		    }
		}
	    }
	}
    }

    # read exons

    my %exons;

    open(F,$f) || die "ERROR 4: Could not open file $f for reading: $!\n";    # exons.dat
    while(<F>) {
	chomp;
	if($_) {
	    my @a=split;
	    if($takegene{$a[0]}) {
		$exons{$a[0]}.=" ".$a[1]." ".$a[2]." ";
	    }
	}
    }
    close(F);


    # read sequences

    my %seqs;

    open(F,$g) || die "ERROR 5: Could not open file $g for reading: $!\n";    # seqs
    while(<F>) {
	chomp;
	my ($name,$seq) = /^(\S+)\s+(\S+)$/;
	$seqs{$name}=$seq;
    }
    close(F);

    # print the features

    my $fe="firstexons.features";
    my $ie="internalexons.features";
    my $le="lastexons.features";
    my $intr="introns.features";

    open(FEx,">$fe");
    open(IEx,">$ie");
    open(LEx,">$le");
    open(Intr,">$intr");

    open(F,$h) || die "ERROR 6: Could not open file $h for reading: $!\n";     # sites.scores

    my ($name,$lastname,$iag,$igt,$itag,$itgt,$ifag,$ifgt);

    $lastname="";

    while(<F>) {
	chomp;
	if(($name) = /^Gene (\S+)$/) {
	    if($takegene{$lastname}) {
		print "Process $lastname...\n";
		processgene($exons{$lastname},$iag,$igt,$seqs{$lastname},$max_ex,$max_in);		
	    }
	
	    $iag=-1;$itag=0;$ifag=0;
	    $igt=-1;$itgt=0;$ifgt=0;
	    if($takegene{$name}) { $lastname=$name; }
	    else { $lastname=""; }
	}
	elsif($lastname) {

	    my @a=split;
	    if($a[0] eq "ag:") {
		$name=$a[1]+2;
		$name=" ".$name." ";
		if(index($exons{$lastname},$name)>-1) {
		    $ag[++$iag]=$a[1];
		    $scoreag[$iag]=$a[2];
		    $itag++;
		}
		else {
		    my $yes=1;
		    if($ifag>$itag) {
			my $roll = int(rand 20);
			$yes=0 if $roll;
		    }
		    if($yes) {
			$ag[++$iag]=$a[1];
			$scoreag[$iag]=$a[2];
			$ifag++;
		    }
		}
	    }
	    if($a[0] eq "gt:") {
		$name=$a[1]-1;
		$name=" ".$name." ";
		if(index($exons{$lastname},$name)>-1) {
		    $gt[++$igt]=$a[1];
		    $scoregt[$igt]=$a[2];
		    $itgt++;
		}
		else {
		    my $yes=1;
		    if($ifgt>$itgt) {
			my $roll = int(rand 20);
			$yes=0 if $roll;
		    }
		    if($yes) {
			$gt[++$igt]=$a[1];
			$scoregt[$igt]=$a[2];
			$ifgt++;
		    }
		}
	    }
	}

    }


    if($takegene{$lastname}) {
	print "Process $lastname...\n";
	processgene($exons{$lastname},$iag,$igt,$seqs{$lastname},$max_ex,$max_in);		
    }
    
    close(F);
    FEx->autoflush(1);
    close(FEx);
    IEx->autoflush(1);
    close(IEx);
    LEx->autoflush(1);
    close(LEx);
    Intr->autoflush(1);
    close(Intr);

    # process single genes

    my $singlex="snglexons.features";
    open(Ex,">$singlex");

    foreach $name (keys %takegene) {
	print "Process $name...\n";
	
	my @ex=split(/\s+/,$exons{$name});

	if($#ex==2) {
	    my $length=$ex[2]-$ex[1]+1;
	    my $exon=substr($seqs{$name},$ex[1]-1,$length-3);
	    my $hexv=hexval($exon);
	    print Ex "$length $hexv 1\n";
	}
	else {
	    my $where=$ex[1]-1;
	    my $cod=substr($seqs{$name},$where,3);
	    my $exon="";
	    while($cod && ($cod ne "tga")&&($cod ne "taa")&&($cod ne "tag")) {
		$exon.=$cod;
		$where+=3;
		$cod=substr($seqs{$name},$where,3);
	    }
	    my $length=length($exon);
	    if($length>=60) {
		my $hexv=hexval($exon);
		print Ex "$length $hexv 2\n";
	    }
	}
    }

    Ex->autoflush(1);
    close(Ex);

}


# oneorf is used by feature_extract 
sub oneorf {
    my $prelex=$_[0];
    my $lengthex=length($prelex);
    
    my $ret=3;

    for(my $frame=0;$frame<3;$frame++) {
	for(my $pos=$frame;$pos+2<$lengthex;$pos+=3)  {
	    my $cod=substr($prelex,$pos,3);
	    if(($cod eq "taa")||($cod eq "tag")||($cod eq "tga")) {
		$ret--;
		last;
	    }
	}
    }

    return($ret);
}

# hexval is used by feature_extract
sub hexval {
    my $prelex=$_[0];
    my $lengthex=length($prelex);

    my @hex;

    for(my $frame=0;$frame<3;$frame++) {
	$hex[$frame]=0;
	for(my $pos=$frame;$pos+5<$lengthex;$pos+=3)  {
	    my $hexamer=uc(substr($prelex,$pos,6));
	    $hex[$frame]+=$vector{$hexamer};
	}
    }

    my $max=$hex[0];
    if($hex[1]>$max) { $max=$hex[1]; }
    if($hex[2]>$max) { $max=$hex[2]; }
	    
    return($max);
}

sub processgene {
   
    my ($exons,$iag,$igt,$seq,$max_ex,$max_in)=@_;
 
    # process gene
    
    my @ex=split(/\s+/,$exons);
    
    if($#ex>2) {
	my $firstgt=$ex[2]+1;
	my $lastag=$ex[$#ex-1]-2;
	my $firstexon=1;

	my ($orf0,$orf1,$orf2,$process,$lenprocess,$last,$length,$exon,$intron,$hexv);
		
	for(my $i=0;$i<=$iag;$i++) {
	    
	    # check here for last exons
	    if($lastag != $ag[$i]) {
		$orf0=1;
		$orf1=1;
		$orf2=1;
		$process=substr($seq,$ag[$i]+1);
		$lenprocess=length($process);
		$last=$ag[$i]+1;
		
		while($orf0 || $orf1 || $orf2) {
		    
		    $length=$last+2-$ag[$i];
		    if($length > $max_ex || $length+3>$lenprocess) { last; }
		    
		    if($orf0) {
			my $cod0=substr($process,0,3);
			if(($cod0 eq "taa")||($cod0 eq "tag")||($cod0 eq "tga")) { 
			    $orf0=0;
			    if($length-3<6) { $hexv=0;}
			    else {
				$exon=substr($seq,$ag[$i]+1,$length-3);
				$hexv=hexval($exon);
			    }
			    print LEx $scoreag[$i]," ",$length-3," ",$hexv," 2\n";
			}
		    }
		
		    if($orf1) {
			my $cod1=substr($process,1,3);
			$length++;
			if(($cod1 eq "taa")||($cod1 eq "tag")||($cod1 eq "tga")) { 
			    $orf1=0;
			    if($length-3<6) { $hexv=0;}
			    else {
				$exon=substr($seq,$ag[$i]+1,$length-3);
				$hexv=hexval($exon);
			    }
			    print LEx $scoreag[$i]," ",$length-3," ",$hexv," 2\n";
			}
		    }
		
		    if($orf2) {
			my $cod2=substr($process,2,3);
			$length++;
			if(($cod2 eq "taa")||($cod2 eq "tag")||($cod2 eq "tga")) { 
			    $orf2=0;
			    if($length-3<6) { $hexv=0;}
			    else {
				$exon=substr($seq,$ag[$i]+1,$length-3);
				$hexv=hexval($exon);
			    }
			    print LEx $scoreag[$i]," ",$length-3," ",$hexv," 2\n";
			}
		    }
		
		    $last+=3;
		    my $temp=substr($process,3);
		    $process=$temp;
		}
	    }
	    else {
		$length=$ex[$#ex]-$ex[$#ex-1]+1-3;
		if($length<6) { $hexv=0;}
		else {
		    $exon=substr($seq,$lastag+1,$length);
		    $hexv=hexval($exon);
		}
		print LEx $scoreag[$i]," ",$length," ",$hexv," 1\n";
	    }

	    # process internal exons
	    for(my $j=0;$j<=$igt;$j++) {
	    
		if($firstexon) {
		    # check here for first exons 
		    if($firstgt == $gt[$j]) {
			$length=$ex[2]-$ex[1]+1;
			if($length<6) { $hexv=0;}
			else {
			    $exon=substr($seq,$ex[1]-1,$length);
			    $hexv=hexval($exon);
			}
			print FEx $scoregt[$j]," ",$length," ",$hexv," 1\n";
		    }
		    else {
			$orf0=1;
			$orf1=1;
			$orf2=1;
			my $lastatg0=0;
			my $lastatg1=0;
			my $lastatg2=0;
			$process=substr($seq,0,$gt[$j]-1);
			$last=$gt[$j]-4;
			while($orf0||$orf1||$orf2) {
			    $length=$gt[$j]-2-$last+1;
			    if($length > $max_ex || $last-3<0) { last; }
			    if($orf0) {
				my $cod0=substr($process,-3);
				if(($cod0 eq "taa")||($cod0 eq "tag")||($cod0 eq "tga")) { 
				    $orf0=0;
				}
				if($cod0 eq "atg") {
				    $lastatg0=$last;
				}
				$last--;
				chop($process);
			    }
			    if($orf1) {
				my $cod1=substr($process,-3);
				if(($cod1 eq "taa")||($cod1 eq "tag")||($cod1 eq "tga")) { 
				    $orf1=0;
				}
				if($cod1 eq "atg") {
				    $lastatg1=$last;
				}
				$last--;
				chop($process);
			    }
			    if($orf2) {
				my $cod2=substr($process,-3);
				if(($cod2 eq "taa")||($cod2 eq "tag")||($cod2 eq "tga")) { 
				    $orf2=0;
				}
				if($cod2 eq "atg") {
				    $lastatg2=$last;
				}
				$last--;
				chop($process);
			    }
			}
			if($lastatg0) {
			    $length=$gt[$j]-2-$lastatg0+1;
			    if($length<6) { $hexv=0;}
			    else {
				$exon=substr($seq,$lastatg0,$length);
				$hexv=hexval($exon);
			    }
			    print FEx $scoregt[$j]," ",$length," ",$hexv," 2\n";
			}
			if($lastatg1) {
			    $length=$gt[$j]-2-$lastatg1+1;
			    if($length<6) { $hexv=0;}
			    else {
				$exon=substr($seq,$lastatg1,$length);
				$hexv=hexval($exon);
			    }
			    print FEx $scoregt[$j]," ",$length," ",$hexv," 2\n";
			}
			if($lastatg2) {
			    $length=$gt[$j]-2-$lastatg2+1;
			    if($length<6) { $hexv=0;}
			    else {
				$exon=substr($seq,$lastatg2,$length);
				$hexv=hexval($exon);
			    }
			    print FEx $scoregt[$j]," ",$length," ",$hexv," 2\n";
			}
		    }
		}

	    
		# now process the internal exons (only if it makes sense)
		if($gt[$j]>$ag[$i]+4) {
		    my $e1=$ag[$i]+2;
		    my $e2=$gt[$j]-1;
		    my $exonedges=" ".$e1." ".$e2." ";
		    $length = $gt[$j]-1-$ag[$i]-1;
		    if($length<=$max_ex) {
			if($length<6) { $hexv=0;}
			else {
			    $exon=substr($seq,$ag[$i]+1,$length);
			    $hexv=hexval($exon);
			}
			if(index($exons,$exonedges)>-1) { # true exon
			    print IEx $scoreag[$i]," ",$scoregt[$j]," ",$length," ",$hexv," 1\n";
			}
			else {
			    if(oneorf($exon) && $length>=6) {
				print IEx $scoreag[$i]," ",$scoregt[$j]," ",$length," ",$hexv," 2\n";
			    }
			}
		    }
		}
	    
		# process introns too
		if($gt[$j]+3<$ag[$i]) {
		    my $e1=$gt[$j]-1;
		    my $e2=$ag[$i]+2;
		    my $exonedges=" ".$e1."  ".$e2." ";
		    $length=$ag[$i]+1-$e1;
		    if($length<=$max_in) {
			if($length<6) { $hexv=0;}
			else {
			    $intron=substr($seq,$gt[$j]-1,$length);
			    $hexv=hexval($intron);
			}
			if(index($exons,$exonedges)>-1) { # true intron
			    print Intr $scoregt[$j]," ",$scoreag[$i]," ",$length," ",$hexv," 1\n";
			}
			else {
			    print Intr $scoregt[$j]," ",$scoreag[$i]," ",$length," ",$hexv," 2\n";
			}
		    }
		}
	    }
	
	    $firstexon=0;
	}
    }
}


# this procedure takes a feature file and transforms it into a balanced
# one (i.e. reduces the no. of features in class 2 by randomly 
# dropping some of them)
sub balance {

    my ($f,$o)=@_;

    my ($n1,$n2);

    open(F,$f) or die "ERROR 7: Couldn't open the features file $f\n";
    while(<F>) {
	chomp;
	my @a=split;
	if($a[$#a]==1) { $n1++;}
	if($a[$#a]==2) { $n2++;}
    }
    close(F);

    if(!$n1) { 
	die "ERROR 146: Feature file $f has not any true examples! Impossible to train the gene finder.\n";
    }

    my $droprate=int($n2/$n1);

    open(F,$f) or die "ERROR 8: Couldn't open the features file $f\n";
    open(O,">$o") or die "ERROR 9: Couldn't create the features file $o for the DT training\n";

    while(<F>){
	chomp;
	my @a=split;
	my $roll=0;
	if($a[$#a]==2) {
	    $roll=int(rand $droprate);
	}
	if(!$roll || $n2<$n1) {
	    print O $_,"\n";
	}
    }

    close(F);
    O->autoflush(1);
    close(O);

}


sub createtree {

    my ($class, $treename, $scriptdir)=@_;
    
    my (@max,@vect);

    for(my $i=1;$i<=$no_of_trees;$i++) {
    	$max[$i]=0;
    }

    for(my $i=1;$i<300;$i++) {
    
	my $status=system("$scriptdir/mktree -a -t $class -p0.15 -s$i > out");
	die "ERROR 10: Could not execute program $scriptdir/mktree!\n" unless $status==0;

	open(F,"out") or die "ERROR 11: Could not open temporary decision tree output file!\n";

	while(<F>) {
	
	    chomp;
	    my @arg=split(/\s+/,$_);

	    if($arg[0] eq "acc.") {
	
		my $leaves=$arg[8];

		if($leaves<=$no_leaves) {
	    
		    my $val=$arg[5];

		    my $equal=0;
		    my $j=$no_of_trees;
		    while($j>0) {
			if($val>$max[$j]) { $j=0; }
			elsif($val==$max[$j]) { 
			    $equal=1;
			    $j=0;
			}
			else {$j--;}
			
		    }
		    
		    $j=1;
		    if(!$equal) {
			while(($j<=$no_of_trees)&&($val>$max[$j])) {
		
			    $max[$j-1]=$max[$j];
			    $max[$j]=$val;
			    $vect[$j-1]=$vect[$j];
			    $vect[$j]=$i;
			    $j++;
			}
		    }
		}
	    }
	}

	close(F);
    }

    my $dtname=$class.".dt";

    for(my $i=1;$i<=$no_of_trees;$i++) {
	
	my $j=$vect[$i];
	my $status=system("$scriptdir/mktree -a -t $class -p0.15 -s$j");
	die "ERROR 12: Could not execute program $scriptdir/mktree!\n" unless $status==0;

	my $tree=$treename.".dt.$i";

	$status=system("cp $dtname trees/$tree");
	die "ERROR 13: Could not copy $dtname to trees/." unless $status==0;
    }

}

sub printtreenames {
    my ($output,$name)=@_;

    open(F,">>$output") or die "ERROR 14: Could not open $output file for writing!\n";

    for(my $i=1;$i<11;$i++) {
	print F "$name.dt.$i\n";
    }

    close(F);
}


# oneorf is used by feature_extract 
#sub oneorf {
#    my $prelex=$_[0];
#    my $ret=3;
#    my @frame;
#    my @test=split(/tga|taa|tag/,$prelex);
#    my $length=0;
#    my $i=0;
    
#    $frame[0]=1;
#    $frame[1]=1;
#    $frame[2]=1;

#    while($ret && $i<=$#test) {
#	$length+=length($test[$i])+3;
#	my $val=$length % 3;
#	$frame[$val]=0;
#	$ret=$frame[0]+$frame[1]+$frame[2];
#	$i++;
#    }

#    return($ret);
#}
